# Values formatted like "_env:YESOD_ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:YESOD_STATIC_DIR:static"
host:           "_env:YESOD_HOST:*4" # any IPv4 host
port:           "_env:YESOD_PORT:3000" # NB: The port `yesod devel` uses is distinct from this value. Set the `yesod devel` port from the command line.
ip-from-header: "_env:YESOD_IP_FROM_HEADER:false"

# Default behavior: determine the application root from the request headers.
# Uncomment to set an explicit approot
# approot:        "_env:YESOD_APPROOT:http://localhost:3000"

# By default, `yesod devel` runs in development, and built executables use
# production settings (see below). To override this, use the following:
#
# development: false

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false
# auth-dummy-login : false

# NB: If you need a numeric value (e.g. 123) to parse as a String, wrap it in single quotes (e.g. "_env:YESOD_PGPASS:'123'")
# See https://github.com/yesodweb/yesod/wiki/Configuration#parsing-numeric-values-as-strings

database:
  user:     "_env:YESOD_PGUSER:user"
  password: "_env:YESOD_PGPASS:password"
  host:     "_env:YESOD_PGHOST:localhost"
  port:     "_env:YESOD_PGPORT:5432"
  # See config/test-settings.yml for an override during tests
  database: "_env:YESOD_PGDATABASE:dbname"
  poolsize: "_env:YESOD_PGPOOLSIZE:10"

redis:
  host:      "_env:REDIS_HOST:localhost"          # host name or address
  port:      "_env:REDIS_PORT:6379"               # you can specify either port
  # socket: /run/redis.socket                     # or unix socket path
  password:  "_env:REDIS_PASSWORD:"               # if not specified then no password used
  database:  "_env:REDIS_DATABASE:0"              # database number to connect to
  max-connections: "_env:REDIS_MAX_CONNECTIONS:5" # max 5 connections in pool
  max-idle-time:   "_env:REDIS_MAX_IDLE_TIME:30"  # max 30 idle time in pool

copyright: Insert copyright statement here
#analytics: UA-YOURCODE

########################
# Houbou Constant Value
########################
# Blog setting rec key
blog-setting-id: HB_BLOG_SETTING

# Session time out(min)
session-timeout: 120

# email paramater length
login-email-length: 256
login-passwd-length: 256

# list count
list-selector:
  - 10
  - 25
  - 50
  - 100
  - 150
  - 200

# Post Blog Param Max String Len
post-title-length: 1000
post-text-length: 100000
slug-text-length: 1000
tag-length: 600
tag-one-length: 30
og-image-length: 600
og-title-length: 300
og-url-length: 600
og-sitename-length: 300
og-desc-length: 300
og-pagetype-length: 16

# page meta
meta-length-description: 1200
meta-length-keywords: 100
meta-length-robots: 50

# Frame html and Css Max String Len
frame-name-length: 300
frame-html-length: 100000
frame-css-length: 100000

# Free page html and Css Max String Len
free-title-length: 300
free-html-length: 100000
free-css-length: 100000

# Blog setting param Max String Len
blog-set-blog-name-length: 300
blog-set-blog-url-length: 300
blog-set-post-num-max: 10
blog-set-media-url-length: 600
blog-set-media-dir-length: 600
blog-set-sesstion-timeout-min: 30
blog-set-sesstion-timeout-max: 360
blog-set-adstxt-length: 300
# 1024 x 1024  = 1048576M MAX
blog-set-upload-size-max: 1048576
blog-set-author-length: 200
blog-set-desc-length: 1500

# User info param Max Len
user-acc-email-length: 500
user-acc-passwd-min-length: 6
user-acc-passwd-max-length: 500
user-acc-username-length: 150
user-acc-profile-length: 80

# Media Title Max String Len
media-title-length: 100
